/********************************************************************************
** Form generated from reading UI file 'dialog.ui'
**
** Created by: Qt User Interface Compiler version 5.15.1
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_DIALOG_H
#define UI_DIALOG_H

#include <QtCore/QVariant>
#include <QtWidgets/QApplication>
#include <QtWidgets/QCheckBox>
#include <QtWidgets/QDialog>
#include <QtWidgets/QFrame>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QListWidget>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QScrollArea>
#include <QtWidgets/QSpinBox>
#include <QtWidgets/QTabWidget>
#include <QtWidgets/QVBoxLayout>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_Dialog
{
public:
    QTabWidget *tabWidget;
    QWidget *Calculateur;
    QLineEdit *commandLine;
    QFrame *atomKeyboard;
    QLabel *label_6;
    QLabel *label_7;
    QScrollArea *scrollArea_2;
    QWidget *scrollFun1;
    QVBoxLayout *scrollFun1Layout;
    QScrollArea *scrollArea_5;
    QWidget *scrollVar1;
    QVBoxLayout *scrollVar1Layout;
    QPushButton *ClearButton;
    QPushButton *DelButton;
    QPushButton *SpaceButton;
    QPushButton *EnterButton;
    QListWidget *listWidget;
    QTabWidget *tabOpeAlpha;
    QWidget *tabOpe;
    QPushButton *pushButton_23;
    QPushButton *pushButton_43;
    QPushButton *pushButton_6;
    QPushButton *pushButton_34;
    QPushButton *pushButton_2;
    QPushButton *pushButton_24;
    QPushButton *pushButton_5;
    QPushButton *pushButton_14;
    QPushButton *pushButton_33;
    QPushButton *pushButton_27;
    QPushButton *pushButton_40;
    QPushButton *pushButton_32;
    QPushButton *pushButton_46;
    QPushButton *pushButton_7;
    QPushButton *pushButton_18;
    QPushButton *pushButton_31;
    QPushButton *pushButton_42;
    QPushButton *pushButton_19;
    QPushButton *pushButton_9;
    QPushButton *pushButton_35;
    QPushButton *pushButton_22;
    QPushButton *pushButton_17;
    QPushButton *pushButton_38;
    QPushButton *pushButton_3;
    QPushButton *pushButton_8;
    QPushButton *pushButton_16;
    QPushButton *pushButton_39;
    QPushButton *pushButton_11;
    QPushButton *pushButton_26;
    QPushButton *btn0;
    QPushButton *pushButton;
    QPushButton *pushButton_25;
    QPushButton *pushButton_4;
    QPushButton *UNDObutton;
    QPushButton *pushButton_10;
    QPushButton *pushButton_45;
    QPushButton *pushButton_37;
    QPushButton *pushButton_36;
    QPushButton *pushButton_29;
    QPushButton *pushButton_15;
    QPushButton *pushButton_28;
    QPushButton *pushButton_41;
    QPushButton *pushButton_30;
    QPushButton *pushButton_13;
    QPushButton *pushButton_20;
    QPushButton *pushButton_21;
    QPushButton *pushButton_47;
    QPushButton *pushButton_59;
    QPushButton *UNDObutton_2;
    QWidget *tabAlpha;
    QPushButton *pushButton_44;
    QPushButton *pushButton_48;
    QPushButton *pushButton_49;
    QPushButton *pushButton_50;
    QPushButton *pushButton_51;
    QPushButton *pushButton_52;
    QPushButton *pushButton_53;
    QPushButton *pushButton_54;
    QPushButton *pushButton_55;
    QPushButton *pushButton_56;
    QPushButton *pushButton_57;
    QPushButton *pushButton_58;
    QPushButton *pushButton_96;
    QPushButton *pushButton_97;
    QPushButton *pushButton_98;
    QPushButton *pushButton_99;
    QPushButton *pushButton_100;
    QPushButton *pushButton_101;
    QPushButton *pushButton_102;
    QPushButton *pushButton_103;
    QPushButton *pushButton_104;
    QPushButton *pushButton_105;
    QPushButton *pushButton_106;
    QPushButton *pushButton_107;
    QPushButton *pushButton_108;
    QPushButton *pushButton_109;
    QPushButton *pushButton_110;
    QPushButton *pushButton_111;
    QPushButton *pushButton_112;
    QWidget *Parametres;
    QFrame *frame;
    QCheckBox *checkBox;
    QCheckBox *checkBox_2;
    QSpinBox *spinBox;
    QLabel *label_4;
    QFrame *frame_2;
    QLineEdit *varName;
    QLineEdit *varValue;
    QLabel *label_8;
    QLabel *label_9;
    QPushButton *varSave;
    QScrollArea *scrollAreaVar2;
    QWidget *scrollVar2;
    QVBoxLayout *verticalLayout_5;
    QPushButton *varSuppr;
    QLabel *label;
    QLabel *label_2;
    QLabel *label_3;
    QFrame *frame_3;
    QLineEdit *funName;
    QLineEdit *funValue;
    QLabel *label_10;
    QLabel *label_11;
    QPushButton *funSave;
    QScrollArea *scrollAreaFun2;
    QWidget *scrollFun2;
    QVBoxLayout *verticalLayout_3;
    QPushButton *funSuppr;
    QLineEdit *errorLine;
    QPushButton *closeErrorLine;

    void setupUi(QDialog *Dialog)
    {
        if (Dialog->objectName().isEmpty())
            Dialog->setObjectName(QString::fromUtf8("Dialog"));
        Dialog->resize(1241, 644);
        Dialog->setStyleSheet(QString::fromUtf8("QFrame{border:1px solid black;}\n"
"QLabel{border:none;}\n"
"QPushButton{background-color:#363e3f;border:1px solid #252c2d;color:white;}\n"
"*{background-color:#282c2d;color:white;}QTabBar::tab::selected{background-color:#282c2d;color:white;}QTabBar::tab{padding:5px 15px; border: 1px solid #393c3e; background-color:black; }QTabWidget::pane { border: 1px solid #393c3e;}\n"
"QLineEdit{background-color:#363e3f;border:1px solid #252c2d;color:white;padding:5px;margin:3px;width:50px;}"));
        tabWidget = new QTabWidget(Dialog);
        tabWidget->setObjectName(QString::fromUtf8("tabWidget"));
        tabWidget->setGeometry(QRect(10, 20, 1221, 611));
        tabWidget->setAutoFillBackground(false);
        tabWidget->setStyleSheet(QString::fromUtf8(""));
        Calculateur = new QWidget();
        Calculateur->setObjectName(QString::fromUtf8("Calculateur"));
        commandLine = new QLineEdit(Calculateur);
        commandLine->setObjectName(QString::fromUtf8("commandLine"));
        commandLine->setEnabled(true);
        commandLine->setGeometry(QRect(400, 490, 361, 31));
        commandLine->setReadOnly(true);
        atomKeyboard = new QFrame(Calculateur);
        atomKeyboard->setObjectName(QString::fromUtf8("atomKeyboard"));
        atomKeyboard->setGeometry(QRect(840, 30, 351, 431));
        atomKeyboard->setFrameShape(QFrame::StyledPanel);
        atomKeyboard->setFrameShadow(QFrame::Raised);
        label_6 = new QLabel(atomKeyboard);
        label_6->setObjectName(QString::fromUtf8("label_6"));
        label_6->setGeometry(QRect(20, 10, 161, 41));
        QFont font;
        font.setPointSize(15);
        label_6->setFont(font);
        label_7 = new QLabel(atomKeyboard);
        label_7->setObjectName(QString::fromUtf8("label_7"));
        label_7->setGeometry(QRect(20, 210, 161, 41));
        label_7->setFont(font);
        scrollArea_2 = new QScrollArea(atomKeyboard);
        scrollArea_2->setObjectName(QString::fromUtf8("scrollArea_2"));
        scrollArea_2->setGeometry(QRect(20, 250, 311, 161));
        scrollArea_2->setStyleSheet(QString::fromUtf8("QPushButton{height:20px;margin:5px;}\342\231\246"));
        scrollArea_2->setWidgetResizable(true);
        scrollFun1 = new QWidget();
        scrollFun1->setObjectName(QString::fromUtf8("scrollFun1"));
        scrollFun1->setGeometry(QRect(0, 0, 309, 159));
        scrollFun1->setStyleSheet(QString::fromUtf8("QPushButton{height:25px; }"));
        scrollFun1Layout = new QVBoxLayout(scrollFun1);
        scrollFun1Layout->setObjectName(QString::fromUtf8("scrollFun1Layout"));
        scrollArea_2->setWidget(scrollFun1);
        scrollArea_5 = new QScrollArea(atomKeyboard);
        scrollArea_5->setObjectName(QString::fromUtf8("scrollArea_5"));
        scrollArea_5->setGeometry(QRect(20, 50, 311, 161));
        scrollArea_5->setStyleSheet(QString::fromUtf8("QPushButton{height:20px;margin:5px;}"));
        scrollArea_5->setWidgetResizable(true);
        scrollVar1 = new QWidget();
        scrollVar1->setObjectName(QString::fromUtf8("scrollVar1"));
        scrollVar1->setGeometry(QRect(0, 0, 309, 159));
        scrollVar1->setStyleSheet(QString::fromUtf8("QPushButton{height:25px; }"));
        scrollVar1Layout = new QVBoxLayout(scrollVar1);
        scrollVar1Layout->setObjectName(QString::fromUtf8("scrollVar1Layout"));
        scrollArea_5->setWidget(scrollVar1);
        ClearButton = new QPushButton(Calculateur);
        ClearButton->setObjectName(QString::fromUtf8("ClearButton"));
        ClearButton->setGeometry(QRect(170, 480, 71, 31));
        DelButton = new QPushButton(Calculateur);
        DelButton->setObjectName(QString::fromUtf8("DelButton"));
        DelButton->setGeometry(QRect(260, 480, 71, 31));
        SpaceButton = new QPushButton(Calculateur);
        SpaceButton->setObjectName(QString::fromUtf8("SpaceButton"));
        SpaceButton->setGeometry(QRect(80, 480, 71, 31));
        EnterButton = new QPushButton(Calculateur);
        EnterButton->setObjectName(QString::fromUtf8("EnterButton"));
        EnterButton->setGeometry(QRect(760, 490, 71, 31));
        listWidget = new QListWidget(Calculateur);
        listWidget->setObjectName(QString::fromUtf8("listWidget"));
        listWidget->setGeometry(QRect(400, 30, 421, 431));
        listWidget->setFont(font);
        tabOpeAlpha = new QTabWidget(Calculateur);
        tabOpeAlpha->setObjectName(QString::fromUtf8("tabOpeAlpha"));
        tabOpeAlpha->setGeometry(QRect(20, 10, 351, 461));
        tabOpe = new QWidget();
        tabOpe->setObjectName(QString::fromUtf8("tabOpe"));
        pushButton_23 = new QPushButton(tabOpe);
        pushButton_23->setObjectName(QString::fromUtf8("pushButton_23"));
        pushButton_23->setGeometry(QRect(30, 100, 51, 31));
        pushButton_43 = new QPushButton(tabOpe);
        pushButton_43->setObjectName(QString::fromUtf8("pushButton_43"));
        pushButton_43->setGeometry(QRect(270, 260, 51, 31));
        pushButton_6 = new QPushButton(tabOpe);
        pushButton_6->setObjectName(QString::fromUtf8("pushButton_6"));
        pushButton_6->setGeometry(QRect(150, 300, 51, 31));
        pushButton_34 = new QPushButton(tabOpe);
        pushButton_34->setObjectName(QString::fromUtf8("pushButton_34"));
        pushButton_34->setGeometry(QRect(90, 140, 51, 31));
        pushButton_2 = new QPushButton(tabOpe);
        pushButton_2->setObjectName(QString::fromUtf8("pushButton_2"));
        pushButton_2->setGeometry(QRect(90, 260, 51, 31));
        pushButton_24 = new QPushButton(tabOpe);
        pushButton_24->setObjectName(QString::fromUtf8("pushButton_24"));
        pushButton_24->setGeometry(QRect(270, 180, 51, 31));
        pushButton_5 = new QPushButton(tabOpe);
        pushButton_5->setObjectName(QString::fromUtf8("pushButton_5"));
        pushButton_5->setGeometry(QRect(90, 300, 51, 31));
        pushButton_14 = new QPushButton(tabOpe);
        pushButton_14->setObjectName(QString::fromUtf8("pushButton_14"));
        pushButton_14->setGeometry(QRect(210, 300, 51, 31));
        pushButton_33 = new QPushButton(tabOpe);
        pushButton_33->setObjectName(QString::fromUtf8("pushButton_33"));
        pushButton_33->setGeometry(QRect(30, 140, 51, 31));
        pushButton_27 = new QPushButton(tabOpe);
        pushButton_27->setObjectName(QString::fromUtf8("pushButton_27"));
        pushButton_27->setGeometry(QRect(210, 220, 51, 31));
        pushButton_40 = new QPushButton(tabOpe);
        pushButton_40->setObjectName(QString::fromUtf8("pushButton_40"));
        pushButton_40->setGeometry(QRect(270, 380, 51, 31));
        pushButton_32 = new QPushButton(tabOpe);
        pushButton_32->setObjectName(QString::fromUtf8("pushButton_32"));
        pushButton_32->setGeometry(QRect(270, 140, 51, 31));
        pushButton_46 = new QPushButton(tabOpe);
        pushButton_46->setObjectName(QString::fromUtf8("pushButton_46"));
        pushButton_46->setGeometry(QRect(270, 60, 51, 31));
        pushButton_7 = new QPushButton(tabOpe);
        pushButton_7->setObjectName(QString::fromUtf8("pushButton_7"));
        pushButton_7->setGeometry(QRect(30, 340, 51, 31));
        pushButton_18 = new QPushButton(tabOpe);
        pushButton_18->setObjectName(QString::fromUtf8("pushButton_18"));
        pushButton_18->setGeometry(QRect(150, 60, 51, 31));
        pushButton_31 = new QPushButton(tabOpe);
        pushButton_31->setObjectName(QString::fromUtf8("pushButton_31"));
        pushButton_31->setGeometry(QRect(270, 100, 51, 31));
        pushButton_42 = new QPushButton(tabOpe);
        pushButton_42->setObjectName(QString::fromUtf8("pushButton_42"));
        pushButton_42->setGeometry(QRect(270, 300, 51, 31));
        pushButton_19 = new QPushButton(tabOpe);
        pushButton_19->setObjectName(QString::fromUtf8("pushButton_19"));
        pushButton_19->setGeometry(QRect(30, 60, 51, 31));
        pushButton_9 = new QPushButton(tabOpe);
        pushButton_9->setObjectName(QString::fromUtf8("pushButton_9"));
        pushButton_9->setGeometry(QRect(150, 340, 51, 31));
        pushButton_35 = new QPushButton(tabOpe);
        pushButton_35->setObjectName(QString::fromUtf8("pushButton_35"));
        pushButton_35->setGeometry(QRect(150, 140, 51, 31));
        pushButton_22 = new QPushButton(tabOpe);
        pushButton_22->setObjectName(QString::fromUtf8("pushButton_22"));
        pushButton_22->setGeometry(QRect(30, 180, 51, 31));
        pushButton_17 = new QPushButton(tabOpe);
        pushButton_17->setObjectName(QString::fromUtf8("pushButton_17"));
        pushButton_17->setGeometry(QRect(90, 60, 51, 31));
        pushButton_38 = new QPushButton(tabOpe);
        pushButton_38->setObjectName(QString::fromUtf8("pushButton_38"));
        pushButton_38->setGeometry(QRect(150, 100, 51, 31));
        pushButton_3 = new QPushButton(tabOpe);
        pushButton_3->setObjectName(QString::fromUtf8("pushButton_3"));
        pushButton_3->setGeometry(QRect(150, 260, 51, 31));
        pushButton_3->setFocusPolicy(Qt::NoFocus);
        pushButton_3->setAutoFillBackground(false);
        pushButton_8 = new QPushButton(tabOpe);
        pushButton_8->setObjectName(QString::fromUtf8("pushButton_8"));
        pushButton_8->setGeometry(QRect(90, 340, 51, 31));
        pushButton_16 = new QPushButton(tabOpe);
        pushButton_16->setObjectName(QString::fromUtf8("pushButton_16"));
        pushButton_16->setGeometry(QRect(210, 380, 51, 31));
        pushButton_39 = new QPushButton(tabOpe);
        pushButton_39->setObjectName(QString::fromUtf8("pushButton_39"));
        pushButton_39->setGeometry(QRect(210, 100, 51, 31));
        pushButton_11 = new QPushButton(tabOpe);
        pushButton_11->setObjectName(QString::fromUtf8("pushButton_11"));
        pushButton_11->setGeometry(QRect(150, 380, 51, 31));
        pushButton_26 = new QPushButton(tabOpe);
        pushButton_26->setObjectName(QString::fromUtf8("pushButton_26"));
        pushButton_26->setGeometry(QRect(150, 220, 51, 31));
        btn0 = new QPushButton(tabOpe);
        btn0->setObjectName(QString::fromUtf8("btn0"));
        btn0->setGeometry(QRect(90, 380, 51, 31));
        pushButton = new QPushButton(tabOpe);
        pushButton->setObjectName(QString::fromUtf8("pushButton"));
        pushButton->setGeometry(QRect(30, 260, 51, 31));
        pushButton_25 = new QPushButton(tabOpe);
        pushButton_25->setObjectName(QString::fromUtf8("pushButton_25"));
        pushButton_25->setGeometry(QRect(30, 220, 51, 31));
        pushButton_4 = new QPushButton(tabOpe);
        pushButton_4->setObjectName(QString::fromUtf8("pushButton_4"));
        pushButton_4->setGeometry(QRect(30, 300, 51, 31));
        UNDObutton = new QPushButton(tabOpe);
        UNDObutton->setObjectName(QString::fromUtf8("UNDObutton"));
        UNDObutton->setGeometry(QRect(210, 20, 51, 31));
        pushButton_10 = new QPushButton(tabOpe);
        pushButton_10->setObjectName(QString::fromUtf8("pushButton_10"));
        pushButton_10->setGeometry(QRect(30, 380, 51, 31));
        pushButton_45 = new QPushButton(tabOpe);
        pushButton_45->setObjectName(QString::fromUtf8("pushButton_45"));
        pushButton_45->setGeometry(QRect(210, 60, 51, 31));
        pushButton_37 = new QPushButton(tabOpe);
        pushButton_37->setObjectName(QString::fromUtf8("pushButton_37"));
        pushButton_37->setGeometry(QRect(90, 100, 51, 31));
        pushButton_36 = new QPushButton(tabOpe);
        pushButton_36->setObjectName(QString::fromUtf8("pushButton_36"));
        pushButton_36->setGeometry(QRect(210, 140, 51, 31));
        pushButton_29 = new QPushButton(tabOpe);
        pushButton_29->setObjectName(QString::fromUtf8("pushButton_29"));
        pushButton_29->setGeometry(QRect(90, 180, 51, 31));
        pushButton_15 = new QPushButton(tabOpe);
        pushButton_15->setObjectName(QString::fromUtf8("pushButton_15"));
        pushButton_15->setGeometry(QRect(210, 340, 51, 31));
        pushButton_28 = new QPushButton(tabOpe);
        pushButton_28->setObjectName(QString::fromUtf8("pushButton_28"));
        pushButton_28->setGeometry(QRect(270, 220, 51, 31));
        pushButton_41 = new QPushButton(tabOpe);
        pushButton_41->setObjectName(QString::fromUtf8("pushButton_41"));
        pushButton_41->setGeometry(QRect(270, 340, 51, 31));
        pushButton_30 = new QPushButton(tabOpe);
        pushButton_30->setObjectName(QString::fromUtf8("pushButton_30"));
        pushButton_30->setGeometry(QRect(90, 220, 51, 31));
        pushButton_13 = new QPushButton(tabOpe);
        pushButton_13->setObjectName(QString::fromUtf8("pushButton_13"));
        pushButton_13->setGeometry(QRect(210, 260, 51, 31));
        pushButton_20 = new QPushButton(tabOpe);
        pushButton_20->setObjectName(QString::fromUtf8("pushButton_20"));
        pushButton_20->setGeometry(QRect(210, 180, 51, 31));
        pushButton_21 = new QPushButton(tabOpe);
        pushButton_21->setObjectName(QString::fromUtf8("pushButton_21"));
        pushButton_21->setGeometry(QRect(150, 180, 51, 31));
        pushButton_47 = new QPushButton(tabOpe);
        pushButton_47->setObjectName(QString::fromUtf8("pushButton_47"));
        pushButton_47->setGeometry(QRect(90, 20, 51, 31));
        pushButton_47->setFocusPolicy(Qt::NoFocus);
        pushButton_59 = new QPushButton(tabOpe);
        pushButton_59->setObjectName(QString::fromUtf8("pushButton_59"));
        pushButton_59->setGeometry(QRect(30, 20, 51, 31));
        pushButton_59->setFocusPolicy(Qt::NoFocus);
        UNDObutton_2 = new QPushButton(tabOpe);
        UNDObutton_2->setObjectName(QString::fromUtf8("UNDObutton_2"));
        UNDObutton_2->setGeometry(QRect(270, 20, 51, 31));
        tabOpeAlpha->addTab(tabOpe, QString());
        tabAlpha = new QWidget();
        tabAlpha->setObjectName(QString::fromUtf8("tabAlpha"));
        pushButton_44 = new QPushButton(tabAlpha);
        pushButton_44->setObjectName(QString::fromUtf8("pushButton_44"));
        pushButton_44->setGeometry(QRect(30, 90, 51, 31));
        pushButton_48 = new QPushButton(tabAlpha);
        pushButton_48->setObjectName(QString::fromUtf8("pushButton_48"));
        pushButton_48->setGeometry(QRect(90, 90, 51, 31));
        pushButton_49 = new QPushButton(tabAlpha);
        pushButton_49->setObjectName(QString::fromUtf8("pushButton_49"));
        pushButton_49->setGeometry(QRect(150, 90, 51, 31));
        pushButton_50 = new QPushButton(tabAlpha);
        pushButton_50->setObjectName(QString::fromUtf8("pushButton_50"));
        pushButton_50->setGeometry(QRect(210, 90, 51, 31));
        pushButton_51 = new QPushButton(tabAlpha);
        pushButton_51->setObjectName(QString::fromUtf8("pushButton_51"));
        pushButton_51->setGeometry(QRect(270, 90, 51, 31));
        pushButton_52 = new QPushButton(tabAlpha);
        pushButton_52->setObjectName(QString::fromUtf8("pushButton_52"));
        pushButton_52->setGeometry(QRect(30, 130, 51, 31));
        pushButton_53 = new QPushButton(tabAlpha);
        pushButton_53->setObjectName(QString::fromUtf8("pushButton_53"));
        pushButton_53->setGeometry(QRect(90, 130, 51, 31));
        pushButton_54 = new QPushButton(tabAlpha);
        pushButton_54->setObjectName(QString::fromUtf8("pushButton_54"));
        pushButton_54->setGeometry(QRect(210, 130, 51, 31));
        pushButton_55 = new QPushButton(tabAlpha);
        pushButton_55->setObjectName(QString::fromUtf8("pushButton_55"));
        pushButton_55->setGeometry(QRect(150, 130, 51, 31));
        pushButton_56 = new QPushButton(tabAlpha);
        pushButton_56->setObjectName(QString::fromUtf8("pushButton_56"));
        pushButton_56->setGeometry(QRect(270, 130, 51, 31));
        pushButton_57 = new QPushButton(tabAlpha);
        pushButton_57->setObjectName(QString::fromUtf8("pushButton_57"));
        pushButton_57->setGeometry(QRect(30, 170, 51, 31));
        pushButton_58 = new QPushButton(tabAlpha);
        pushButton_58->setObjectName(QString::fromUtf8("pushButton_58"));
        pushButton_58->setGeometry(QRect(90, 170, 51, 31));
        pushButton_96 = new QPushButton(tabAlpha);
        pushButton_96->setObjectName(QString::fromUtf8("pushButton_96"));
        pushButton_96->setGeometry(QRect(210, 170, 51, 31));
        pushButton_97 = new QPushButton(tabAlpha);
        pushButton_97->setObjectName(QString::fromUtf8("pushButton_97"));
        pushButton_97->setGeometry(QRect(150, 170, 51, 31));
        pushButton_98 = new QPushButton(tabAlpha);
        pushButton_98->setObjectName(QString::fromUtf8("pushButton_98"));
        pushButton_98->setGeometry(QRect(270, 170, 51, 31));
        pushButton_99 = new QPushButton(tabAlpha);
        pushButton_99->setObjectName(QString::fromUtf8("pushButton_99"));
        pushButton_99->setGeometry(QRect(30, 210, 51, 31));
        pushButton_100 = new QPushButton(tabAlpha);
        pushButton_100->setObjectName(QString::fromUtf8("pushButton_100"));
        pushButton_100->setGeometry(QRect(90, 210, 51, 31));
        pushButton_101 = new QPushButton(tabAlpha);
        pushButton_101->setObjectName(QString::fromUtf8("pushButton_101"));
        pushButton_101->setGeometry(QRect(210, 210, 51, 31));
        pushButton_102 = new QPushButton(tabAlpha);
        pushButton_102->setObjectName(QString::fromUtf8("pushButton_102"));
        pushButton_102->setGeometry(QRect(150, 210, 51, 31));
        pushButton_103 = new QPushButton(tabAlpha);
        pushButton_103->setObjectName(QString::fromUtf8("pushButton_103"));
        pushButton_103->setGeometry(QRect(270, 210, 51, 31));
        pushButton_104 = new QPushButton(tabAlpha);
        pushButton_104->setObjectName(QString::fromUtf8("pushButton_104"));
        pushButton_104->setGeometry(QRect(30, 250, 51, 31));
        pushButton_105 = new QPushButton(tabAlpha);
        pushButton_105->setObjectName(QString::fromUtf8("pushButton_105"));
        pushButton_105->setGeometry(QRect(90, 250, 51, 31));
        pushButton_106 = new QPushButton(tabAlpha);
        pushButton_106->setObjectName(QString::fromUtf8("pushButton_106"));
        pushButton_106->setGeometry(QRect(210, 250, 51, 31));
        pushButton_107 = new QPushButton(tabAlpha);
        pushButton_107->setObjectName(QString::fromUtf8("pushButton_107"));
        pushButton_107->setGeometry(QRect(150, 250, 51, 31));
        pushButton_108 = new QPushButton(tabAlpha);
        pushButton_108->setObjectName(QString::fromUtf8("pushButton_108"));
        pushButton_108->setGeometry(QRect(270, 250, 51, 31));
        pushButton_109 = new QPushButton(tabAlpha);
        pushButton_109->setObjectName(QString::fromUtf8("pushButton_109"));
        pushButton_109->setGeometry(QRect(30, 290, 51, 31));
        pushButton_110 = new QPushButton(tabAlpha);
        pushButton_110->setObjectName(QString::fromUtf8("pushButton_110"));
        pushButton_110->setGeometry(QRect(150, 290, 51, 31));
        pushButton_111 = new QPushButton(tabAlpha);
        pushButton_111->setObjectName(QString::fromUtf8("pushButton_111"));
        pushButton_111->setGeometry(QRect(210, 290, 51, 31));
        pushButton_112 = new QPushButton(tabAlpha);
        pushButton_112->setObjectName(QString::fromUtf8("pushButton_112"));
        pushButton_112->setGeometry(QRect(270, 290, 51, 31));
        tabOpeAlpha->addTab(tabAlpha, QString());
        tabWidget->addTab(Calculateur, QString());
        Parametres = new QWidget();
        Parametres->setObjectName(QString::fromUtf8("Parametres"));
        frame = new QFrame(Parametres);
        frame->setObjectName(QString::fromUtf8("frame"));
        frame->setGeometry(QRect(40, 30, 351, 491));
        frame->setStyleSheet(QString::fromUtf8(""));
        frame->setFrameShape(QFrame::StyledPanel);
        frame->setFrameShadow(QFrame::Raised);
        checkBox = new QCheckBox(frame);
        checkBox->setObjectName(QString::fromUtf8("checkBox"));
        checkBox->setGeometry(QRect(10, 20, 251, 19));
        QFont font1;
        font1.setPointSize(12);
        checkBox->setFont(font1);
        checkBox_2 = new QCheckBox(frame);
        checkBox_2->setObjectName(QString::fromUtf8("checkBox_2"));
        checkBox_2->setGeometry(QRect(10, 60, 321, 19));
        checkBox_2->setFont(font1);
        spinBox = new QSpinBox(frame);
        spinBox->setObjectName(QString::fromUtf8("spinBox"));
        spinBox->setGeometry(QRect(10, 100, 42, 31));
        spinBox->setValue(10);
        label_4 = new QLabel(frame);
        label_4->setObjectName(QString::fromUtf8("label_4"));
        label_4->setGeometry(QRect(60, 100, 281, 31));
        QFont font2;
        font2.setPointSize(12);
        font2.setKerning(true);
        label_4->setFont(font2);
        label_4->setAutoFillBackground(false);
        label_4->setStyleSheet(QString::fromUtf8(""));
        frame_2 = new QFrame(Parametres);
        frame_2->setObjectName(QString::fromUtf8("frame_2"));
        frame_2->setGeometry(QRect(440, 30, 351, 491));
        frame_2->setStyleSheet(QString::fromUtf8(""));
        frame_2->setFrameShape(QFrame::StyledPanel);
        frame_2->setFrameShadow(QFrame::Raised);
        varName = new QLineEdit(frame_2);
        varName->setObjectName(QString::fromUtf8("varName"));
        varName->setGeometry(QRect(10, 50, 331, 31));
        varValue = new QLineEdit(frame_2);
        varValue->setObjectName(QString::fromUtf8("varValue"));
        varValue->setGeometry(QRect(10, 120, 331, 31));
        label_8 = new QLabel(frame_2);
        label_8->setObjectName(QString::fromUtf8("label_8"));
        label_8->setGeometry(QRect(10, 20, 71, 21));
        label_8->setFont(font1);
        label_9 = new QLabel(frame_2);
        label_9->setObjectName(QString::fromUtf8("label_9"));
        label_9->setGeometry(QRect(10, 90, 101, 21));
        label_9->setFont(font1);
        varSave = new QPushButton(frame_2);
        varSave->setObjectName(QString::fromUtf8("varSave"));
        varSave->setGeometry(QRect(250, 460, 80, 21));
        scrollAreaVar2 = new QScrollArea(frame_2);
        scrollAreaVar2->setObjectName(QString::fromUtf8("scrollAreaVar2"));
        scrollAreaVar2->setGeometry(QRect(10, 160, 331, 291));
        scrollAreaVar2->setStyleSheet(QString::fromUtf8("QPushButton{height:20px;margin:5px;}"));
        scrollAreaVar2->setWidgetResizable(true);
        scrollVar2 = new QWidget();
        scrollVar2->setObjectName(QString::fromUtf8("scrollVar2"));
        scrollVar2->setGeometry(QRect(0, 0, 329, 289));
        scrollVar2->setStyleSheet(QString::fromUtf8("QPushButton{height:20px;margin:5px;}"));
        verticalLayout_5 = new QVBoxLayout(scrollVar2);
        verticalLayout_5->setObjectName(QString::fromUtf8("verticalLayout_5"));
        scrollAreaVar2->setWidget(scrollVar2);
        varSuppr = new QPushButton(frame_2);
        varSuppr->setObjectName(QString::fromUtf8("varSuppr"));
        varSuppr->setGeometry(QRect(160, 460, 80, 21));
        label = new QLabel(Parametres);
        label->setObjectName(QString::fromUtf8("label"));
        label->setGeometry(QRect(40, 10, 111, 16));
        label->setFont(font1);
        label->setAutoFillBackground(false);
        label_2 = new QLabel(Parametres);
        label_2->setObjectName(QString::fromUtf8("label_2"));
        label_2->setGeometry(QRect(440, 10, 71, 16));
        label_2->setFont(font1);
        label_3 = new QLabel(Parametres);
        label_3->setObjectName(QString::fromUtf8("label_3"));
        label_3->setGeometry(QRect(830, 10, 81, 16));
        label_3->setFont(font1);
        frame_3 = new QFrame(Parametres);
        frame_3->setObjectName(QString::fromUtf8("frame_3"));
        frame_3->setGeometry(QRect(830, 30, 351, 491));
        frame_3->setStyleSheet(QString::fromUtf8(""));
        frame_3->setFrameShape(QFrame::StyledPanel);
        frame_3->setFrameShadow(QFrame::Raised);
        funName = new QLineEdit(frame_3);
        funName->setObjectName(QString::fromUtf8("funName"));
        funName->setGeometry(QRect(10, 50, 331, 31));
        funValue = new QLineEdit(frame_3);
        funValue->setObjectName(QString::fromUtf8("funValue"));
        funValue->setGeometry(QRect(10, 120, 331, 31));
        label_10 = new QLabel(frame_3);
        label_10->setObjectName(QString::fromUtf8("label_10"));
        label_10->setGeometry(QRect(10, 20, 71, 21));
        label_10->setFont(font1);
        label_11 = new QLabel(frame_3);
        label_11->setObjectName(QString::fromUtf8("label_11"));
        label_11->setGeometry(QRect(10, 90, 101, 21));
        label_11->setFont(font1);
        funSave = new QPushButton(frame_3);
        funSave->setObjectName(QString::fromUtf8("funSave"));
        funSave->setGeometry(QRect(250, 460, 80, 21));
        scrollAreaFun2 = new QScrollArea(frame_3);
        scrollAreaFun2->setObjectName(QString::fromUtf8("scrollAreaFun2"));
        scrollAreaFun2->setGeometry(QRect(10, 160, 331, 291));
        scrollAreaFun2->setStyleSheet(QString::fromUtf8("QPushButton{height:20px;margin:5px;}"));
        scrollAreaFun2->setWidgetResizable(true);
        scrollFun2 = new QWidget();
        scrollFun2->setObjectName(QString::fromUtf8("scrollFun2"));
        scrollFun2->setGeometry(QRect(0, 0, 329, 289));
        scrollFun2->setStyleSheet(QString::fromUtf8("QPushButton{height:20px;margin:5px;}"));
        verticalLayout_3 = new QVBoxLayout(scrollFun2);
        verticalLayout_3->setObjectName(QString::fromUtf8("verticalLayout_3"));
        scrollAreaFun2->setWidget(scrollFun2);
        funSuppr = new QPushButton(frame_3);
        funSuppr->setObjectName(QString::fromUtf8("funSuppr"));
        funSuppr->setGeometry(QRect(160, 460, 80, 21));
        tabWidget->addTab(Parametres, QString());
        errorLine = new QLineEdit(Dialog);
        errorLine->setObjectName(QString::fromUtf8("errorLine"));
        errorLine->setEnabled(true);
        errorLine->setGeometry(QRect(260, 10, 721, 31));
        errorLine->setLayoutDirection(Qt::RightToLeft);
        errorLine->setStyleSheet(QString::fromUtf8("background:#f44455;color:white;border-radius:0px;border:none;font-weight:bold;padding-left:20px;padding-top:5px;padding-bottom:5px;font-family:Arial;"));
        errorLine->setReadOnly(true);
        closeErrorLine = new QPushButton(Dialog);
        closeErrorLine->setObjectName(QString::fromUtf8("closeErrorLine"));
        closeErrorLine->setGeometry(QRect(950, 9, 31, 31));
        closeErrorLine->setStyleSheet(QString::fromUtf8("border:none;\n"
"background:transparent;"));

        retranslateUi(Dialog);

        tabWidget->setCurrentIndex(1);
        listWidget->setCurrentRow(-1);
        tabOpeAlpha->setCurrentIndex(0);


        QMetaObject::connectSlotsByName(Dialog);
    } // setupUi

    void retranslateUi(QDialog *Dialog)
    {
        Dialog->setWindowTitle(QCoreApplication::translate("Dialog", "CompUT", nullptr));
        label_6->setText(QCoreApplication::translate("Dialog", "Variables", nullptr));
        label_7->setText(QCoreApplication::translate("Dialog", "Fonctions", nullptr));
        ClearButton->setText(QCoreApplication::translate("Dialog", "EFFACER", nullptr));
        DelButton->setText(QCoreApplication::translate("Dialog", "\342\206\220", nullptr));
        SpaceButton->setText(QCoreApplication::translate("Dialog", "ESPACE", nullptr));
        EnterButton->setText(QCoreApplication::translate("Dialog", "Entrer", nullptr));
        pushButton_23->setText(QCoreApplication::translate("Dialog", "DEN", nullptr));
        pushButton_43->setText(QCoreApplication::translate("Dialog", "CLEAR", nullptr));
        pushButton_6->setText(QCoreApplication::translate("Dialog", "6", nullptr));
        pushButton_34->setText(QCoreApplication::translate("Dialog", ">", nullptr));
        pushButton_2->setText(QCoreApplication::translate("Dialog", "8", nullptr));
        pushButton_24->setText(QCoreApplication::translate("Dialog", "TAN", nullptr));
        pushButton_5->setText(QCoreApplication::translate("Dialog", "5", nullptr));
        pushButton_14->setText(QCoreApplication::translate("Dialog", "-", nullptr));
        pushButton_33->setText(QCoreApplication::translate("Dialog", "<", nullptr));
        pushButton_27->setText(QCoreApplication::translate("Dialog", "ARCCOS", nullptr));
        pushButton_40->setText(QCoreApplication::translate("Dialog", "DUP", nullptr));
        pushButton_32->setText(QCoreApplication::translate("Dialog", "!=", nullptr));
        pushButton_46->setText(QCoreApplication::translate("Dialog", "IFTE", nullptr));
        pushButton_7->setText(QCoreApplication::translate("Dialog", "1", nullptr));
        pushButton_18->setText(QCoreApplication::translate("Dialog", "MOD", nullptr));
        pushButton_31->setText(QCoreApplication::translate("Dialog", "=", nullptr));
        pushButton_42->setText(QCoreApplication::translate("Dialog", "SWAP", nullptr));
        pushButton_19->setText(QCoreApplication::translate("Dialog", "NUM", nullptr));
        pushButton_9->setText(QCoreApplication::translate("Dialog", "3", nullptr));
        pushButton_35->setText(QCoreApplication::translate("Dialog", "<=", nullptr));
        pushButton_22->setText(QCoreApplication::translate("Dialog", "POW", nullptr));
        pushButton_17->setText(QCoreApplication::translate("Dialog", "DIV", nullptr));
        pushButton_38->setText(QCoreApplication::translate("Dialog", "OR", nullptr));
        pushButton_3->setText(QCoreApplication::translate("Dialog", "9", nullptr));
        pushButton_8->setText(QCoreApplication::translate("Dialog", "2", nullptr));
        pushButton_16->setText(QCoreApplication::translate("Dialog", "/", nullptr));
        pushButton_39->setText(QCoreApplication::translate("Dialog", "NOT", nullptr));
        pushButton_11->setText(QCoreApplication::translate("Dialog", ".", nullptr));
        pushButton_26->setText(QCoreApplication::translate("Dialog", "ARCSIN", nullptr));
        btn0->setText(QCoreApplication::translate("Dialog", "0", nullptr));
        pushButton->setText(QCoreApplication::translate("Dialog", "7", nullptr));
        pushButton_25->setText(QCoreApplication::translate("Dialog", "SQRT", nullptr));
        pushButton_4->setText(QCoreApplication::translate("Dialog", "4", nullptr));
        UNDObutton->setText(QCoreApplication::translate("Dialog", "UNDO", nullptr));
        pushButton_10->setText(QCoreApplication::translate("Dialog", "NEG", nullptr));
        pushButton_45->setText(QCoreApplication::translate("Dialog", "IFT", nullptr));
        pushButton_37->setText(QCoreApplication::translate("Dialog", "AND", nullptr));
        pushButton_36->setText(QCoreApplication::translate("Dialog", ">=", nullptr));
        pushButton_29->setText(QCoreApplication::translate("Dialog", "EXP", nullptr));
        pushButton_15->setText(QCoreApplication::translate("Dialog", "*", nullptr));
        pushButton_28->setText(QCoreApplication::translate("Dialog", "ARCTAN", nullptr));
        pushButton_41->setText(QCoreApplication::translate("Dialog", "DROP", nullptr));
        pushButton_30->setText(QCoreApplication::translate("Dialog", "LN", nullptr));
        pushButton_13->setText(QCoreApplication::translate("Dialog", "+", nullptr));
        pushButton_20->setText(QCoreApplication::translate("Dialog", "COS", nullptr));
        pushButton_21->setText(QCoreApplication::translate("Dialog", "SIN", nullptr));
        pushButton_47->setText(QCoreApplication::translate("Dialog", "FORGET", nullptr));
        pushButton_59->setText(QCoreApplication::translate("Dialog", "STO", nullptr));
        UNDObutton_2->setText(QCoreApplication::translate("Dialog", "WHILE", nullptr));
        tabOpeAlpha->setTabText(tabOpeAlpha->indexOf(tabOpe), QCoreApplication::translate("Dialog", "Operateurs", nullptr));
        pushButton_44->setText(QCoreApplication::translate("Dialog", "A", nullptr));
        pushButton_48->setText(QCoreApplication::translate("Dialog", "B", nullptr));
        pushButton_49->setText(QCoreApplication::translate("Dialog", "C", nullptr));
        pushButton_50->setText(QCoreApplication::translate("Dialog", "D", nullptr));
        pushButton_51->setText(QCoreApplication::translate("Dialog", "E", nullptr));
        pushButton_52->setText(QCoreApplication::translate("Dialog", "F", nullptr));
        pushButton_53->setText(QCoreApplication::translate("Dialog", "G", nullptr));
        pushButton_54->setText(QCoreApplication::translate("Dialog", "I", nullptr));
        pushButton_55->setText(QCoreApplication::translate("Dialog", "H", nullptr));
        pushButton_56->setText(QCoreApplication::translate("Dialog", "J", nullptr));
        pushButton_57->setText(QCoreApplication::translate("Dialog", "K", nullptr));
        pushButton_58->setText(QCoreApplication::translate("Dialog", "L", nullptr));
        pushButton_96->setText(QCoreApplication::translate("Dialog", "N", nullptr));
        pushButton_97->setText(QCoreApplication::translate("Dialog", "M", nullptr));
        pushButton_98->setText(QCoreApplication::translate("Dialog", "O", nullptr));
        pushButton_99->setText(QCoreApplication::translate("Dialog", "P", nullptr));
        pushButton_100->setText(QCoreApplication::translate("Dialog", "Q", nullptr));
        pushButton_101->setText(QCoreApplication::translate("Dialog", "S", nullptr));
        pushButton_102->setText(QCoreApplication::translate("Dialog", "R", nullptr));
        pushButton_103->setText(QCoreApplication::translate("Dialog", "T", nullptr));
        pushButton_104->setText(QCoreApplication::translate("Dialog", "U", nullptr));
        pushButton_105->setText(QCoreApplication::translate("Dialog", "V", nullptr));
        pushButton_106->setText(QCoreApplication::translate("Dialog", "X", nullptr));
        pushButton_107->setText(QCoreApplication::translate("Dialog", "W", nullptr));
        pushButton_108->setText(QCoreApplication::translate("Dialog", "Y", nullptr));
        pushButton_109->setText(QCoreApplication::translate("Dialog", "Z", nullptr));
        pushButton_110->setText(QCoreApplication::translate("Dialog", "'", nullptr));
        pushButton_111->setText(QCoreApplication::translate("Dialog", "[", nullptr));
        pushButton_112->setText(QCoreApplication::translate("Dialog", "]", nullptr));
        tabOpeAlpha->setTabText(tabOpeAlpha->indexOf(tabAlpha), QCoreApplication::translate("Dialog", "Alphabet", nullptr));
        tabWidget->setTabText(tabWidget->indexOf(Calculateur), QCoreApplication::translate("Dialog", "Calculateur", nullptr));
        checkBox->setText(QCoreApplication::translate("Dialog", "Masquer le clavier d'operateurs", nullptr));
        checkBox_2->setText(QCoreApplication::translate("Dialog", "Masquer le clavier de Variables/Fonctions", nullptr));
        label_4->setText(QCoreApplication::translate("Dialog", "Nombre d'\303\251l\303\251ments de la pile affich\303\251s", nullptr));
        label_8->setText(QCoreApplication::translate("Dialog", "Nom", nullptr));
        label_9->setText(QCoreApplication::translate("Dialog", "Valeur", nullptr));
        varSave->setText(QCoreApplication::translate("Dialog", "Sauvegarder", nullptr));
        varSuppr->setText(QCoreApplication::translate("Dialog", "Supprimer", nullptr));
        label->setText(QCoreApplication::translate("Dialog", "Parametres", nullptr));
        label_2->setText(QCoreApplication::translate("Dialog", "Variables", nullptr));
        label_3->setText(QCoreApplication::translate("Dialog", "Fonctions", nullptr));
        label_10->setText(QCoreApplication::translate("Dialog", "Nom", nullptr));
        label_11->setText(QCoreApplication::translate("Dialog", "Valeur", nullptr));
        funSave->setText(QCoreApplication::translate("Dialog", "Sauvegarder", nullptr));
        funSuppr->setText(QCoreApplication::translate("Dialog", "Supprimer", nullptr));
        tabWidget->setTabText(tabWidget->indexOf(Parametres), QCoreApplication::translate("Dialog", "Parametres", nullptr));
        errorLine->setText(QString());
        closeErrorLine->setText(QCoreApplication::translate("Dialog", "X", nullptr));
    } // retranslateUi

};

namespace Ui {
    class Dialog: public Ui_Dialog {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_DIALOG_H
